### ISSUE TITLE
【BUG】The provider parameter is incorrect when submitting the Service withdraw-fees transaction

### ISSUE THREAD

**Issue by huang0227** [irismod/service#31]
./iritacli tx service withdraw-fees iaa10v2y2q8exur5jqr7e0dwqlnt4493vz4sahlus9 --from huang1 --chain-id=cschain-bond --node=http://localhost:26957  --home=/huang/bianjie/csrb --memo=ceshiyixiamemeo --fees=1point
Enter keyring passphrase:
{"chain_id":"cschain-bond","account_number":"9","sequence":"12","fee":{"amount":[{"denom":"point","amount":"1"}],"gas":"200000"},"msgs":[{"type":"irismod/service/MsgWithdrawEarnedFees","value":{"owner":"iaa1u825z7xdyp7pr4n0e3vr7r42hmqk6hr25nhyn0","provider":"iaa1u825z7xdyp7pr4n0e3vr7r42hmqk6hr25nhyn0"}}],"memo":"ceshiyixiamemeo"}

confirm transaction before signing and broadcasting [y/N]: n

As you know, the value of the provider parameter entered on the command line displays the address of the sender when submitting the confirmation.And the actual link is also wrong.

**Comment by chengwenxi** [comment]
https://github.com/irismod/service/blob/master/client/cli/tx.go#L882-L889

The length of args is never greater than 1 @secret2830
